### PR TITLE
allow default ordering for getAllEntities

### PR DESCRIPTION
**Pull request by rayzor65**

### CODE REVIEW

**Comment by xiphiaz** [comment]
@rayzor65 please add a unit test

**Comment by rayzor65** [comment]
What is the best way to run unit tests for this. When I try locally I get a pdo exception

**Comment by xiphiaz** [comment]
@rayzor65 From memory I think I just set it up so it was also working in the vagrant vm, so it actually used the same database as spira. @cmsx can you provide more details on local setup of this as you work with the core far more than me.

**Comment by cmsx** [comment]
@xiphiaz I'm runing it on host machine with pgsql and php installed. 
Just call artisan migrate then phpunit.

**Comment by rayzor65** [comment]
Hi guys I am getting issues setting up spira core, I get this during the forum phase.
`Starting spira_data_1
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
> Spira\Build::postInstall
> composer install --working-dir public
mv: cannot stat '/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini': No such file or directory
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
> Spira\Build::buildForum
mv: cannot stat '/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini.disabled': No such file or directory
Connection to 127.0.0.1 closed.
Error spira:forum  install 

Error: Command exited with error status  1 
Error spira:forum install 

Error: Command exited with error status  1 
err 1
Error spira 

Error: undefined
`


If I try to run the tests I get the following results 
Tests: 330, Assertions: 687, Errors: 56, Failures: 9, Skipped: 3

Most the errors say connection refused to 8008 eg
Failed to connect to web port 8008: Connection refused [url] http://web:8008/api/discussions?email=system%40domain.com&method=POST&path=discussions&timestamp=1460708902&username=system&token=b061e8027f6c165b60b7619077bc01dd4307f1c81be54787ec177c9441d4dfea

**Comment by rayzor65** [comment]
@xiphiaz updated PR. Attempted to make StyleCI happy but I think its complaining about silly things, not to mention things that I didn't actually update

**Pull request merged**
